language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

install:
  - npm i

script:
  - npm run test
  - npm run build

deploy:
  on:
    branch: master
    tags: true
  provider: script
  skip_cleanup: true
  script: sh scripts/deploy.sh $TRAVIS_TAG